# Generated by Django 4.2.1 on 2024-03-17 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_customuser_id_alter_customuser_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='birth_date',
            new_name='dob',
        ),
    ]
