# Generated by Django 4.2.1 on 2024-04-08 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_descripton'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descripton',
            new_name='description',
        ),
    ]
